### ISSUE TITLE
Are there any plans to release paintkit as an npm package?

### ISSUE THREAD

**Issue by hand-dot** [seanchas116/paintkit#2]
Hi @seanchas116 
I'm very impressed with your excellent work!

I'm working on a graphic editor with a PDF library called [pdfme](https://github.com/pdfme/pdfme).
And I was hoping to have exactly this kind of UI component...! 
because creating such a UI component is a bit difficult for me...

**Do you have plans to release paintkit as an npm package?**  
**If so, it would be great if you could share something like a roadmap.**

I'd like to contribute if there is something I can help with. (testing, writing docs, etc.)

Thanks!! You are great!!✌️

**Comment by seanchas116** [comment]
I haven't released paintkit as a "ready-to-use" component library because:

* It has many dependencies (styled-component for every components, MobX for some components etc)
* It has [utility functions/classes](https://github.com/seanchas116/paintkit/tree/main/src/util) that are not relevant to UI components
* I have no time to write docs
* I'm thinking of migrating it to Web Components (so it can be used in Macaron documents)

I'd like to release it as a npm package when ↑ are resolved!

**Comment by hand-dot** [comment]
Thanks for replying.
I see... I understand.

So, I'll close this issue.
